name: 'Build ESP Master Sketch'

on:
  - push

jobs:
  compile-sketch:
    name: "Build ESP Master Sketch"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip Arduino Libraries
        run: |
          unzip ./ArduinoLibraries/ESPAsyncTCP-master.zip
          unzip ./ArduinoLibraries/ESPAsyncWebServer-master.zip

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp8266:esp8266:generic"
          platforms: |
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: |
            - ./ESPMaster
          libraries: |
            - name: Arduino_JSON
              version: 0.2.0
            - name: ArduinoOTA
              version: 1.0.12
            - name: NTPClient
              version: 3.2.1
            - name: ezTime
              version: 0.8.3
            - name: LinkedList
              version: 1.3.3
            - name: ESPAsyncWebServer
              source-path: ./ArduinoLibraries/ESPAsyncWebServer-master
            - name: ESPAsyncTCP
              source-path: ./ArduinoLibraries/ESPAsyncTCP-master
          enable-deltas-report: true